[project]
name = "ai-sports-outcome-predictor"
version = "1.0.0"
description = "Lightweight, LLM-first Telegram sports prediction bot (no DB, no heavy ML)"
requires-python = ">=3.11"
dependencies = [
    "python-telegram-bot==20.7",
    "aiohttp>=3.11.0",
    "requests>=2.32.0",
    "numpy>=2.0.0",
    "pandas>=2.2.0",
    "scikit-learn>=1.5.0",
    "google-generativeai>=0.7.2"
]
